language: go

go:
  - tip
  - 1.13.x

before_script:
  - go mod download

script:
  - go build .

notifications:
  email:
    recipients: smallnest@gmail.com
    on_success: change
    on_failure: always
